---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: iam-sync
  namespace: rucio-vre
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure 
          containers:
            - name: iam-sync
              image: ghcr.io/vre-hub/vre-iam-rucio-sync:v0.1.0-109-c9355f9
              volumeMounts:
              - name: rucio-cfg
                mountPath: /opt/rucio/etc/
              env:
              - name: IAM_SERVER
                value: "https://iam-escape.cloud.cnaf.infn.it"
              - name: IAM_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: iam-client
                    key: admin-client_secret
              - name: IAM_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: iam-client
                    key: admin-client_id
              tty: true
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - date; echo Hello from iam-rucio-sync container; 
                pwd; ls;
                echo $IAM_SERVER; python3 /home/sync_iam_rucio.py; echo '* Sync to IAM * Done!'
          volumes:
            - name: rucio-cfg
              secret:
                secretName: escape-service-account
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rucio-noise
  namespace: rucio-vre
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure 
          containers:
            - name: rucio-noise
              image: ghcr.io/vre-hub/vre-rucio-noise:v0.1.0-215-8481de7
              volumeMounts:
              - name: rucio-cfg
                mountPath: /opt/rucio/etc/
              - name: prod-rucio-x509up
                mountPath: /tmp/
              - name: daemons-vre-cafile
                mountPath: /etc/pki/tls/certs/

              env:
              - name: RUCIO_CFG_CLIENT_X509_PROXY 
                valueFrom:
                  secretKeyRef:
                    name: prod-rucio-x509up
                    key: x509up
              tty: true
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - date; ls -l /etc/pki/tls/certs/; ls -l /tmp/; openssl /tmp/x509up -in x509up -text -noout; cd /opt/rucio/etc/; pwd; echo Hello from rucio-noise container; 
                export RUCIO_CONFIG=/opt/rucio/etc/rucio.cfg; echo Exported config; cat /opt/rucio/etc/rucio.cfg; rucio -vvv whoami; 
                cd /tmp/; ls -l; cd /home; export FSIZE=10M; FILE_SIZE=${FSIZE} /bin/bash produce_noise.sh; echo "Rucio noise cronjob ${FSIZE} Done!"
              # - date; pwd; cd /root/.globus/; ls; chmod 400 userkey.pem; cd /opt/rucio/etc/; ls; echo Hello from rucio-noise container; export RUCIO_CONFIG=/opt/rucio/etc/rucio.cfg; echo Exported config; rucio -vvv whoami; FILE_SIZE=10M /bin/bash /home/user/vre/containers/rucio-noise/produce_noise.sh; echo 'DB cleanup Done!'
          volumes:
            - name: rucio-cfg
              secret:
                secretName: escape-service-account
                defaultMode: 0400
            - name: prod-rucio-x509up
              secret:
                secretName: prod-rucio-x509up
            - name: daemons-vre-cafile
              secret:
                secretName: daemons-vre-cafile
---
apiVersion: v1
kind: Pod
metadata:
  name: rucio-client
  namespace: rucio-vre
spec:
  containers:
  - name: rucio-client
    image: ghcr.io/vre-hub/vre-rucio-client:v0.1.0-108-3797d0d
    imagePullPolicy: Always
    env:
    - name: RUCIO_CFG_RUCIO_HOST
      value: "https://vre-rucio.cern.ch"
    - name: RUCIO_CFG_AUTH_HOST
      value: "https://vre-rucio-auth.cern.ch"
    - name: RUCIO_CFG_ACCOUNT
      value: "root"
    - name: RUCIO_CFG_AUTH_TYPE
      value: "userpass"
    - name: RUCIO_CFG_USERNAME
      valueFrom:
        secretKeyRef:
          name: root-account
          key: root-username
    - name: RUCIO_CFG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: root-account
          key: root-password 
    command: ["sleep","3600"]
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi


