---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: iam-sync
  namespace: rucio
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure 
          containers:
            - name: iam-sync
              image: ghcr.io/vre-hub/vre-iam-rucio-sync:latest
              volumeMounts:
              - name: rucio-cfg
                mountPath: /opt/rucio/etc/
              env:
              - name: IAM_SERVER
                value: "https://iam-escape.cloud.cnaf.infn.it"
              - name: IAM_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: iam-client
                    key: admin-client_secret
              - name: IAM_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: iam-client
                    key: admin-client_id
              tty: true
              imagePullPolicy: Always
              command:
              - /bin/sh
              - -c
              - date; echo Hello from iam-rucio-sync container; 
                pwd; ls;
                echo $IAM_SERVER; python3 /home/user/vre/containers/iam-rucio-sync/sync_iam_rucio.py; echo '* Sync to IAM * Done!'
          volumes:
            - name: rucio-cfg
              secret:
                secretName: rucio-cfg
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rucio-noise1
  namespace: rucio
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure 
          containers:
            - name: rucio-noise1
              image: ghcr.io/vre-hub/vre-rucio-noise:latest
              volumeMounts:
              - name: rucio-sso-cfg
                mountPath: /opt/rucio/etc/
              - name: prod-rucio-x509up
                mountPath: /tmp/

              env:
              - name: RUCIO_CFG_CLIENT_X509_PROXY 
                valueFrom:
                  secretKeyRef:
                    name: prod-rucio-x509up
                    key: x509up
              tty: true
              imagePullPolicy: Always
              command:
              - /bin/sh
              - -c
              - date; pwd; cd /opt/rucio/etc/; ls; echo Hello from rucio-noise container; export RUCIO_CONFIG=/opt/rucio/etc/rucio-sso.cfg; echo Exported config; rucio -vvv whoami; FILE_SIZE=10M /bin/bash /home/user/vre/containers/rucio-noise/produce_noise.sh; echo 'DB cleanup Done!'
          volumes:
            - name: rucio-sso-cfg
              secret:
                secretName: rucio-sso-cfg
            - name: prod-rucio-x509up
              secret:
                secretName: prod-rucio-x509up
---
apiVersion: v1
kind: Pod
metadata:
  name: rucio-client
  namespace: rucio
spec:
  containers:
  - name: rucio-client
    image: ghcr.io/vre-hub/vre-rucio-client:latest
    imagePullPolicy: Always
    env:
    - name: RUCIO_CFG_RUCIO_HOST
      value: "https://vre-rucio.cern.ch"
    - name: RUCIO_CFG_AUTH_HOST
      value: "https://vre-rucio-auth.cern.ch"
    - name: RUCIO_CFG_ACCOUNT
      value: "root"
    - name: RUCIO_CFG_AUTH_TYPE
      value: "userpass"
    - name: RUCIO_CFG_USERNAME
      valueFrom:
        secretKeyRef:
          name: root-account
          key: root-username
    - name: RUCIO_CFG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: root-account
          key: root-password 
    command: ["sleep","3600"]
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
