
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-cvmfsplugin
  namespace: kube-system
spec:
  interval: 1m
  url: https://registry.cern.ch/chartrepo/cern
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-cvmfsplugin
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cern/cvmfs-csi
      version: "2.1.1"
      sourceRef:
        kind: HelmRepository
        name: cvmfs-csi
        namespace: kube-system
      interval: 1m
  # VRE wiki explanation: https://github.com/vre-hub/vre/wiki/Components#cvmfs---cern-vm-file-system 
  values:
    nodeplugin:
      tolerations:
        - key: "jupyter-role"
          operator: "Exists"
          effect: "NoSchedule"
---
# Based on docs and snippets from https://github.com/cvmfs-contrib/cvmfs-csi
#
# Create StorageClass for provisioning CVMFS automount volumes,
# and a PersistentVolumeClaim that's fulfilled by the StorageClass.
#
# If Controller plugin is not deployed, follow the example in volume-pv-pvc.yaml.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs
provisioner: cvmfs.csi.cern.ch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs
  namespace: jhub
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      # Volume size value has no effect and is ignored
      # by the driver, but must be non-zero.
      storage: 1
  storageClassName: cvmfs
