apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: cern-monit
  namespace: monit
spec:
  interval: 10m
  url: oci://registry.cern.ch/monit/cern-it-monitoring-kubernetes