# apiVersion: apps/v1
# kind: ConfigMap
# metadata:
#   name: eos-csi-dir-etc-eos
#   namespace: kube-system
# spec:
#   data:
#     fuse.eulake.conf: | 
#       '{"name":"eulake_test","hostport":"eospilot.cern.ch","remotemountdir":"/eos/pilot/eulake/escape/data/","localmountdir":"/eos/eulake/","auth":{"ssskeytab":"/etc/fuse.sss.keytab"}}'
