apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ui
  namespace: rucio

spec:
  releaseName: ui
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: rucio-charts
        namespace: rucio
      interval: 1m
      chart: rucio-ui
      version: 35.0.1

  valuesFrom:
    - kind: Secret
      name: rucio-db
      valuesKey: dbfullstring
      targetPath: config.database.default
  
  values:
    # policyPackages:
    #   enabled: true
    #   packages:
    #   - moduleName: escape_rucio_policy_package
    #     requirement: escape-rucio-policy-package==0.2.2
    #     version: 0.2.2

    secretMounts:
      - secretName: hostcert
        mountPath: /etc/grid-security/hostcert.pem
        subPath: hostcert.pem
      - secretName: hostkey
        mountPath: /etc/grid-security/hostkey.pem
        subPath: hostkey.pem
      - secretName: cafile
        mountPath: /etc/grid-security/ca.pem
        subPath: ca.pem
      - secretName: idpsecrets
        mountPath: /opt/rucio/etc/idpsecrets.json
        subPath: idpsecrets.json
      - volumeName: escape-rucio-policy-package-init
        secretFullName: escape-rucio-policy-package
        mountPath: /usr/local/lib/python3.9/site-packages/escape_rucio_policy_package/__init__.py
        subPath: __init__.py
      - volumeName: escape-rucio-policy-package-permission
        secretFullName: escape-rucio-policy-package
        mountPath: /usr/local/lib/python3.9/site-packages/escape_rucio_policy_package/permission.py
        subPath: permission.py
      - volumeName: escape-rucio-policy-package-schema
        secretFullName: escape-rucio-policy-package
        mountPath: /usr/local/lib/python3.9/site-packages/escape_rucio_policy_package/schema.py
        subPath: schema.py


    replicaCount: 1
    exposeErrorLogs: True
    useSSL: true
    useDeprecatedImplicitSecrets: false

    service:
      type: LoadBalancer
      port: 443
      targetPort: 443
      protocol: TCP
      name: https
      useSSL: true

    image:
      repository: rucio/rucio-ui
      tag: release-35.8.0
      pullPolicy: Always

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1

    minReadySeconds: 5

    proxy:
      rucioProxy: "vre-rucio.cern.ch"
      rucioProxyScheme: "https"
      rucioAuthProxy: "vre-rucio-auth.cern.ch"
      rucioAuthProxyScheme: "https"

    # Followinf documentation [1] this should be enable, but when auth via x509 there is and
    #  error that no rucio account is mapped to that cert --> Disenabiling it
    # [1] https://github.com/rucio/helm-charts/tree/master/charts/rucio-ui#ingress

    # ingress:
    #   enabled: true
    #   annotations:
    #     kubernetes.io/ingress.class: nginx
    #     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    #     nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #   path: /
    #   hosts: 
    #     - vre-rucio-ui.cern.ch
        
    ## values used to configure apache
    # httpd_config:
    #   legacy_dn: "False"
    #   rucio_hostname: "vre-rucio-ui.cern.ch"
      
    httpd_config:
      mpm_mode: "event"
      rucio_hostname: "vre-rucio-ui.cern.ch"
      # start_servers: "1"
      # min_spare_threads: "1"
      # max_spare_threads: "20"
      # threads_per_child: "5"
      # max_clients: "20"
      # max_requests_per_child: "8192"
      # timeout: 300
      # min_spare_servers: "1"
      # max_spare_servers: "5"
      # server_limit: "10"
      # keep_alive: "On"
      # keep_alive_timeout: "5"
      # max_keep_alive_requests: "128"
      # threads_limit: "128"
      # max_request_workers: "1280"
      # max_connections_per_child: "2048"

    config:
      policy:
        permission: "generic"
        schema: "generic"
        lfn2pfn_algorithm_default: "identity"

      oidc:
        idpsecrets: "/opt/rucio/etc/idpsecrets.json"
        admin_issuer: "escape"

      # credentials:
      #   gcs: "/opt/rucio/etc/rse-accounts.cfg"

    resources:
      limits:
        cpu: 200m
        memory: 2000Mi
      requests:
        cpu: 200m
        memory: 1000Mi
